package codexharness

import (
	"encoding/json"

	"github.com/futrx-com/remote.futrx.com/internal/agent"
)

// These are the account/rateLimits shapes generated by the pinned app-server
// protocol. The app server sends account/rateLimits/updated with every token
// count that carries rate limits, so any turn that reaches the model reports
// its account's windows. Updates are sparse: a window an update leaves out
// keeps its last reading. A snapshot may describe several metered products;
// only the Codex bucket describes the subscription displayed by Remote.
//
// A run does not also call account/rateLimits/read: the app server finishes
// in-flight requests before it exits when its input closes, so an unanswered
// read would hold back the end of every short turn. The Usage tab's on-demand
// reads start an app server of their own (codex/plan_usage.go).
type appServerRateLimits struct {
	RateLimits          json.RawMessage            `json:"rateLimits"`
	RateLimitsByLimitID map[string]json.RawMessage `json:"rateLimitsByLimitId"`
}

type appServerRateLimitSnapshot struct {
	LimitID   string                    `json:"limitId"`
	Primary   *appServerRateLimitWindow `json:"primary"`
	Secondary *appServerRateLimitWindow `json:"secondary"`
}

type appServerRateLimitWindow struct {
	UsedPercent        *float64 `json:"usedPercent"`
	WindowDurationMins *int64   `json:"windowDurationMins"`
	ResetsAt           *int64   `json:"resetsAt"`
}

// RateLimitQuotas reads the Codex subscription's windows from an
// account/rateLimits notification or read response. A window is recognized
// by its five-hour or seven-day duration, and other products are ignored.
func RateLimitQuotas(raw json.RawMessage, now int64) []agent.Quota {
	var limits appServerRateLimits
	if json.Unmarshal(raw, &limits) != nil {
		return nil
	}
	bucket := limits.RateLimits
	if limits.RateLimitsByLimitID != nil {
		bucket = limits.RateLimitsByLimitID["codex"]
	}
	var snapshot appServerRateLimitSnapshot
	if json.Unmarshal(bucket, &snapshot) != nil || (snapshot.LimitID != "" && snapshot.LimitID != "codex") {
		return nil
	}
	// A legacy single-bucket snapshot may omit limitId. Explicitly identified
	// products and multi-bucket responses must never fall back to that default.
	windows := make(map[agent.QuotaWindow]agent.Quota, 2)
	for _, source := range []*appServerRateLimitWindow{snapshot.Primary, snapshot.Secondary} {
		if source == nil || source.UsedPercent == nil || *source.UsedPercent < 0 || source.WindowDurationMins == nil {
			continue
		}
		var window agent.QuotaWindow
		switch *source.WindowDurationMins {
		case 300:
			window = agent.QuotaWindowSession
		case 10080:
			window = agent.QuotaWindowWeekly
		default:
			continue
		}
		if _, exists := windows[window]; exists {
			continue
		}
		quota := agent.Quota{Window: window, UsedPercent: source.UsedPercent, MeasuredAt: now}
		if source.ResetsAt != nil && *source.ResetsAt > 0 {
			quota.ResetsAt = *source.ResetsAt
		}
		windows[window] = quota
	}
	var readings []agent.Quota
	for _, window := range []agent.QuotaWindow{agent.QuotaWindowSession, agent.QuotaWindowWeekly} {
		if quota, exists := windows[window]; exists {
			readings = append(readings, quota)
		}
	}
	return readings
}

func (parser *appServerEventParser) quotaEvents(now int64, method string, raw json.RawMessage) []agent.Event {
	if parser.req.Provider != agent.ProviderCodex {
		return nil
	}
	var events []agent.Event
	for _, quota := range RateLimitQuotas(raw, now) {
		events = append(events, parser.event(now, method, agent.EventQuotaUpdated, raw, func(event *agent.Event) {
			event.Quota = &quota
		}))
	}
	return events
}
