package applications

import (
	"fmt"

	"github.com/futrx-com/remote.futrx.com/pkg/applications"
)

// backendModuleFile is the go.mod compiled for an application's backend. Its
// module path matches the application's location in the catalog module so
// imports between the composition root and child host packages resolve both in this checkout
// and in the generated build directory. The SDK keeps its canonical import
// path through the replace below.
func (b *Builder) backendModuleFile(applicationID string) string {
	return fmt.Sprintf(`// Generated by the remote.futrx backend host. Do not edit.
module futrx.local/catalog/applications/%s/backend

go %s

require (
	%s v0.0.0
	%s %s
)

require (
%s)

replace %s => ../sdk
`,
		applicationID,
		b.pins.goVersion,
		applications.ModulePath,
		goPluginModule, b.pins.require(goPluginModule, goPluginFallbackVersion),
		b.pins.indirectBlock(applications.ModulePath, goPluginModule),
		applications.ModulePath,
	)
}

// sdkModuleFile is the go.mod of the materialized SDK. It carries the same
// pins so the two modules agree without a workspace file.
func (b *Builder) sdkModuleFile() string {
	return fmt.Sprintf(`// Generated by the remote.futrx backend host. Do not edit.
module %s

go %s

require %s %s

require (
%s)
`,
		applications.ModulePath,
		b.pins.goVersion,
		goPluginModule, b.pins.require(goPluginModule, goPluginFallbackVersion),
		b.pins.indirectBlock(applications.ModulePath, goPluginModule),
	)
}

const (
	goPluginModule = "github.com/hashicorp/go-plugin"
	// goPluginFallbackVersion is used only when build info is unavailable,
	// which in practice means a test binary. TestGoPluginFallbackMatchesGoMod
	// keeps it in step with the server's own requirement.
	goPluginFallbackVersion = "v1.8.0"
)
